apiVersion: v1
kind: Service
metadata:
        name: file-server-service
spec:
        selector:
                app: file-server
        ports:
                - protocol: "TCP"
                  port: 6000
                  targetPort: 5000
        type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: file-server
spec:
        selector:
                matchLabels:
                        app: file-server
        replicas: 1
        template:
                metadata:
                        labels:
                                app: file-server
                spec:
                        containers:
                                - name: file-server
                                  image: localhost:5000/file-server:latest
                                  ports:
                                          - containerPort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
        name: serviceport
        annotations:
                kubernetes.io/ingress.class: traefik
spec:
        rules:
                - host: serviceport
                  http:
                          paths:
                                  - path: /
                                    backend:
                                            serviceName: file-server-service
                                            servicePort: 6000


